// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtOkjszivwWtszaGOWr0z44ZrZ5noKjWw',
    appId: '1:102628235425:web:72e70b75744adc684a78e0',
    messagingSenderId: '102628235425',
    projectId: 'terms-5d921',
    authDomain: 'terms-5d921.firebaseapp.com',
    storageBucket: 'terms-5d921.appspot.com',
    measurementId: 'G-ZTZHXHM5HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtAfWYXCGmmwqxiLOCrddNHhw9SxPdKSU',
    appId: '1:102628235425:android:a9a4a20c421574854a78e0',
    messagingSenderId: '102628235425',
    projectId: 'terms-5d921',
    storageBucket: 'terms-5d921.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ9W-PHM1GSPkZo80z1LuB5SCI4wm9fYg',
    appId: '1:102628235425:ios:4f3c242d5c2837c54a78e0',
    messagingSenderId: '102628235425',
    projectId: 'terms-5d921',
    storageBucket: 'terms-5d921.appspot.com',
    iosClientId: '102628235425-uvts5i6kmsbm3hujais8hdrcjvsiuq5g.apps.googleusercontent.com',
    iosBundleId: 'com.terms.org.terms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ9W-PHM1GSPkZo80z1LuB5SCI4wm9fYg',
    appId: '1:102628235425:ios:dbfd1b4e00c6ef464a78e0',
    messagingSenderId: '102628235425',
    projectId: 'terms-5d921',
    storageBucket: 'terms-5d921.appspot.com',
    iosClientId: '102628235425-2r7agffrtv3ctcuct1fb8bu2kqslfk1b.apps.googleusercontent.com',
    iosBundleId: 'terms',
  );
}
